### ISSUE TITLE
[Feature Request / Bug ] Emoji option

### ISSUE THREAD

**Issue by binury** [DFurnes/purer#1]
On line 148 of pure.zsh you append a ⚠️ warning sign emoji to the prompt if the previously executed task returns an error.
```
	# show indicator if previous command failed
	preprompt+="%(?.. ⚠️️ )"
```
Unfortunately, some terminal emulators have difficulty displaying emojis which can cause weird input glitching due to the abnormal character width of the symbol.

Therefore I propose providing an interface environment variable `PURER_EMOJI` for the purpose of setting the indicator to either an emoji ⚠️ or its regular unicode equivalent ⚠︎. 

An alternative, more user-friendly option would be to automatically determine the display capabilities of the terminal and change the character dynamically. I think however that this will always be an imperfect solution as some terminals may technically support it but then fail to do so in reality.

**Comment by binury** [comment]
P.S.: if you were curious, we are currently experiencing this in [Hyper](https://hyper.is/)

**Comment by DFurnes** [comment]
Thanks for the issue! I totally agree this isn't great.

I've just published an update which adds back the prompt symbol at the beginning of the line and colors that instead of appending the emoji, which seems more faithful to the original Pure anyways. 😄
