### ISSUE TITLE
Normal mode color remains if enter (<CR>) is pressed

### ISSUE THREAD

**Issue by mariogillazaro** [DFurnes/purer#5]
### General information

- Pure version: 1.5.4
- ZSH version: 5.4.1
- Terminal program & version: Terminal 2.8
- Operating system: Mac Os High Sierra 10.13.1 
- ZSH framework: None 

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
Normal mode color remains on new line, even though mode is not enabled

### Reproduction steps

1. Press ESC to enter normal mode
2. Press Enter
3. Type anything

Expected behavior should be that you're needed to press `i` to enter insert mode or prompt indicator should be in insert mode

### My `.zshrc`:

```
bindkey -v
autoload -U promptinit; promptinit
prompt purer
```

**Comment by DFurnes** [comment]
This is fixed in v1.5.5! Thanks for the bug report!
